### ISSUE TITLE
Managing mods for multiple servers (survival vs creative for example)

### ISSUE THREAD

**Issue by ChristopherHaws** [packwiz/packwiz#163]
I am searching for a way to simply the management of my server which contains a creative and survival world which each have slightly different mods installed.

# Pain Points
- Keeping track of what each mod does can get hard when packs get large (100+ mods)
- Keeping the configuration files in sync between two modpacks that are 90% identical is a challenge

## Option 1: Modpack references
One option would be to allow for modpacks to reference other modpacks. To reference another modpack, you could run the command `packwiz ref|reference add [path-or-url-to-another-pack.toml-file]` which would add an option to your `pack.toml` file:
```toml
[option]
references = [
	"https://modpack-url/pack.toml",
	"../common/pack.toml"
]
```

**Conflict Resolution:**
Packwiz should then use last in wins conflict resolution. For example, if `https://modpack-url/pack.toml` has v1 of a mod and `../common/pack.toml` has v2 of a mod, v2 should be used. If `../common/pack.toml` has v2 of a mod and the current modpack has v3 of a mod, v3 should be used. This gives the current modpack the ability to override any of the mods from the base pack if needed.

#### Pros
- Can reference modpacks from another location
- Can organize mods into smaller modpacks, for example optimization mods, quality of life mods, etc could each be their own pack that all get rolled up into one larger pack.

#### Cons
- Have to deal with conflict resolution
- If the other modpack goes away, yours is then broken
- If a referenced pack updates, your back could break

## Option 2: Mod tags and multiple pack.toml files
Another option would be to allow for modpacks to add tags to mods directly and allow the inclusion or exclusion of mods based on the configuration in the pack file. If there are no tags, then the mod is always included.

For example, given the following mod files:
```toml
# ./mods/fabric-api.pw.toml
name = "Fabric API"
filename = "fabric-api-0.67.0+1.19.2.jar"
side = "both"
```

```toml
# ./mods/deathlog.pw.toml
name = "DeathLog"
filename = "deathlog-0.2.11+1.19.jar"
side = "both"
tags = ["survival"]
```

```toml
# ./mods/worldedit.pw.toml
name = "WorldEdit"
filename = "worldedit-mod-7.2.12.jar"
side = "client"
tags = ["creative"]
```

```toml
# ./pack-survival.toml
name = "survival"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
tags-include = ["survival"]
```

```toml
# ./pack-creative.toml
name = "creative"
author = "chaws"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
include-tags = ["creative"]
```

With this setup, if you configure packwiz-installer to point to `pack-survival.toml` you will get FabricAPI and DeathLog. If you configure packwiz-installer to point to `pack-creative.toml` you will get FabricAPI and WorldEdit.

#### Pros
- All of the mods in your pack(s) live in the same repo and are versioned together
- No chances of conflicting versions or files

#### Cons
- Mods are not organized into groups (this could be solved by storing the category from modrinth/curseforge in the metadata and having a command to export a report of all the mods installed grouped by category)
- Not reusable
