### ISSUE TITLE
[Feature] Add a link to the mod in the `.pw.toml` file

### ISSUE THREAD

**Issue by ChristopherHaws** [packwiz/packwiz#174]
Hey, would it be possible to add a new property in the `.pw.toml` file that is simply a link to the mod on the given platform? Something like:

```toml
name = "Fabric API"
filename = "fabric-api-0.69.0+1.19.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/25Hm7c3j/fabric-api-0.69.0%2B1.19.2.jar"
hash-format = "sha1"
hash = "91ccd8078d374160dcbe176512b203fbd3a5e923"

[update]
[update.curseforge]
file-id = 4162908
project-id = 306612
project-url = "https://www.curseforge.com/minecraft/mc-mods/fabric-api"
file-url = "https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/4162908"

[update.modrinth]
mod-id = "P7dR8mSH"
version = "25Hm7c3j"
mod-url = "https://modrinth.com/mod/fabric-api"
version-url = "https://modrinth.com/mod/fabric-api/version/0.69.0+1.19.2"
```

I find myself wanting to navigate to the mod's url's often when trying configure the mods. I also have a script I am making to update my readme with a list of all of the mods and want to include links to the mod pages.

Thanks! :)
