### ISSUE TITLE
Feature: Mod Version Blacklist

### ISSUE THREAD

**Issue by ChristopherHaws** [packwiz/packwiz#180]
I have quite a large mod list that often has mod incompatibilities, especially between different versions of mods. Whenever I find a mod that is causing a crash or is conflicting with another mod mod, I have to keep using an old version until there is a new version that I can check if the issue is fixed.

Right now I keep track of versions that I know are bad in text file, but it would be really nice if I could add an array of blacklisted versions of a mod in the mod's `.pw.toml` file.

For example:
```toml
[update]
[update.modrinth]
mod-id = "P7dR8mSH"
version = "qbOkGdTB"
blacklisted-versions = ["mrB7EiW4"]

[update.curseforge]
project-id = 306612
file-id = 4302462
blacklisted-file-ids = [4287704]
```
