### ISSUE TITLE
Is it possible to have local mods in a modpack?

### ISSUE THREAD

**Issue by Pandademic** [packwiz/packwiz#189]
something like:
```toml
# mods/supercoolmenu.toml

name = "My Super Cool Menu For My Modpack"
filename = "SuperCoolMenu.jar"
side = "client"

[download]
url = "../bin/SuperCoolMenu.jar"
hash-format = "sha1"
hash = "as73enkas8jf99askfoe712k997gblkynas90"
```

Is this possible currently?
