### ISSUE TITLE
is there a way to include the pre-launch command and packwiz-installer jars in your modpack

### ISSUE THREAD

**Issue by walksanatora** [packwiz/packwiz#214]
(asking so that I can bundle the auto-update without having the users manually configure it)

**Comment by comp500** [comment]
In Prism/MultiMC/ATLauncher sure, just add the prelaunch command and packwiz-installer-bootstrap JAR, then export it as a MultiMC pack. You can then give users the zip (or a link to it) and the launcher will pick up the prelaunch command and run packwiz-installer.

**Comment by walksanatora** [comment]
i was thinking something like `packwiz export --auto-update "some url for packwiz here"` to make it automatic (because my prism launcher is being broken and wont let me override instance settings)

**Comment by comp500** [comment]
You can manually edit `instance.cfg` to set `OverrideCommands=true` and `PreLaunchCommand="$INST_JAVA" -jar packwiz-installer-bootstrap.jar [url]`. For a command to generate such a zip for you, there is already an issue at https://github.com/packwiz/packwiz/issues/76

**Comment by copygirl** [comment]
I recently wrote a bash script that creates a Prism Launcher compatible instance .zip file from scratch:
https://gist.github.com/copygirl/ec93c25628b083d4f25bd48259b6d505

It works by reading some additional fields from the `pack.toml`:
```toml
name = "Heckcore"
author = "copygirl"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[publish]
url = "https://example.com/copygirl/heckcore"
memory = 6144

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
```
I personally thought this would make publishing easier, instead of having to provide the URL as an argument to the script, since I already need to read out other values from the pack file. But the script could be adjusted to take it as an argument instead.

Also, perhaps with this as reference, since it appears pretty straight-forward, someone could implement the same functionality as a packwiz command..?
