### ISSUE TITLE
`packwiz serve` does not work with `meta-folder-base`

### ISSUE THREAD

**Issue by xieve** [packwiz/packwiz#264]
This is my directory structure:
```
src/
|- mods/
|- config/
|- index.toml
pack.toml
```

pack.toml states:
```toml
[index]
file = "src/index.toml"

[options]
meta-folder-base = "src"
```

`packwiz cf export` works as expected, exporting everything from `src` to `overrides`. `packwiz serve` creates a `src` folder inside the instance folder and downloads the files in there.
